### ISSUE TITLE
GPIO Interrupts do not appear to work

### ISSUE THREAD

**Issue by jontrulson** [intel-iot-devkit/zmraa#41]
Hi,

I am setting up an interrupt to trigger on GPIO 2.  This is for the Arduino 101, Zephyr 1.6.

Calling mraa_gpio_isr() succeeds (no error is returned), however interrupts fail to be triggered.

`mraa_gpio_isr(dev->gpio, MRAA_GPIO_EDGE_RISING, &wfs_flow_isr, dev`)

_wfs_flow_dev_ is the interrupt function, and _dev_ is the device context I am supplying.

Any clues?

**Comment by whbruce** [comment]
I ran a test with GPIO #4 on Arduino 101, Zephyr 1.7 and it worked as expected.

**Comment by jontrulson** [comment]
Yes, once I updated to Zephyr 1.7 and new SDK, it all worked as expected.  I'll close this.
